# Generated by Django 5.0.4 on 2024-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.FloatField(default=0)),
                ('ean', models.CharField(blank=True, max_length=512, null=True)),
                ('color', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_cost', models.FloatField(default=0)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('acceptance_datetime', models.DateTimeField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
