# Generated by Django 5.0.4 on 2024-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0002_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='id',
        ),
        migrations.AddField(
            model_name='config',
            name='base_url',
            field=models.CharField(default='google.com', max_length=512, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
