# Generated by Django 5.0.4 on 2024-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0003_remove_config_id_config_base_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping_cost',
            new_name='shipping_price',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
