# Generated by Django 5.0.4 on 2024-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0004_rename_shipping_cost_product_shipping_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='Price', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.CharField(blank=True, default='Shipping Price', max_length=512, null=True),
        ),
    ]
