# Generated by Django 5.0.4 on 2024-04-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0005_alter_product_price_alter_product_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='Not Found', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, default='Not Found', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='Not Found', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='Not Found', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, default='Not Found', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, default='Not Found', max_length=512, null=True),
        ),
    ]
