# Generated by Django 5.0.4 on 2024-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0006_alter_product_color_alter_product_ean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.CharField(blank=True, default='Not Found', max_length=512, null=True),
        ),
    ]
