# Generated by Django 5.0.4 on 2024-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0007_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Not Found', max_length=512, null=True)),
                ('url', models.CharField(blank=True, default='Not Found', max_length=512, null=True)),
                ('price', models.CharField(blank=True, default='Not Found', max_length=512, null=True)),
                ('ean', models.CharField(blank=True, default='Not Found', max_length=512, null=True)),
                ('color', models.CharField(blank=True, default='Not Found', max_length=512, null=True)),
                ('shipping_price', models.CharField(blank=True, default='Not Found', max_length=512, null=True)),
                ('stock_status', models.CharField(blank=True, default='Not Found', max_length=512, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('acceptance_datetime', models.DateTimeField(blank=True, null=True)),
                ('product_image', models.BinaryField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.EmailField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
