# Generated by Django 5.0.4 on 2024-05-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0008_pricematch_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='color_selector',
        ),
        migrations.RemoveField(
            model_name='config',
            name='ean_selector',
        ),
        migrations.RemoveField(
            model_name='pricematch',
            name='color',
        ),
    ]
