# Generated by Django 5.0.4 on 2024-06-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0009_remove_config_color_selector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('base_url', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
