# Generated by Django 5.0.4 on 2024-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slowest_element_selector', models.CharField(blank=True, max_length=512)),
                ('cookie_selector', models.CharField(blank=True, max_length=512)),
                ('specification_selector', models.CharField(blank=True, max_length=512)),
                ('price_selector', models.CharField(blank=True, max_length=512)),
                ('name_selector', models.CharField(blank=True, max_length=512)),
                ('ean_selector', models.CharField(blank=True, max_length=512)),
                ('color_selector', models.CharField(blank=True, max_length=512)),
                ('stock_status_selector', models.CharField(blank=True, max_length=512)),
                ('shipping_price_selector', models.CharField(blank=True, max_length=512)),
                ('currency', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
